1. PL/SQL stored procedure to change the status of a course to 1 if the current date is between the start & end date of the course and make it zero if it is not.
CREATE OR REPLACE PROCEDURE STATUS_CHANGE AS
BEGIN
DECLARE
CourseDesc COURSE%ROWTYPE;
CURSOR COURSE_DETAILS IS SELECT * FROM COURSE;
BEGIN
OPEN COURSE_DETAILS;
LOOP
FETCH COURSE_DETAILS INTO CourseDesc;
EXIT WHEN (COURSE_DETAILS%NOTFOUND);
IF(SYSDATE >= CourseDesc.START_DATE AND SYSDATE <= CourseDesc.END_DATE + 1)THEN
IF(CourseDesc.STATUS != 1)THEN
UPDATE COURSE SET STATUS = 1 WHERE COURSE_ID = CourseDesc.COURSE_ID;
END IF;
ELSE
IF(CourseDesc.STATUS != 0)THEN
UPDATE COURSE SET STATUS = 0 WHERE COURSE_ID = CourseDesc.COURSE_ID;
END IF;
END IF;
END LOOP;
CLOSE COURSE_DETAILS;
END;
END STATUS_CHANGE;
Procedure Call:
SET SERVEROUTPUT ON;
BEGIN
STATUS_CHANGE;
END;
